name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: "Run Specific job"
        type: boolean
        required: false
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true
        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on:  ubuntu-latest
    if: ${{ inputs.run-job }}
    steps:
      - name: Printing Custom Message
        run: echo "${{ inputs.custom_message }}"

      - name: Printing run-job boolean value
        run: echo "${{ inputs.run-job }}"